src/Web/Controllers/JobInfoController.cs
using System.Linq;
using AutoMapper;
using Cerberus.Domain.Interface.Services;
using Cerberus.Domain.Model;
using Cerberus.Web.Enum;
using Cerberus.Web.Filters;
using Cerberus.Web.ViewModel.JobInfo;
using Cerberus.Web.WebLogic;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Cerberus.Utility;
using Cerberus.Web.Extensions;
using Gatekeeper.AspModules.ActionFilter;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Cerberus.Web.Controllers
{
    [AuthorizeUserFilterFactory(Scope = (int)AvailableScope.JobInfo)]
    public class JobInfoController : BaseController
    {
        private readonly IJobInfoService _jobInfoService;
        private readonly IJobService _jobService;
        private readonly IMapper _mapper;


        public JobInfoController(IJobInfoService jobInfoService, IJobService jobService, IMapper mapper)
        {
            _jobInfoService = jobInfoService;
            _jobService = jobService;
            _mapper = mapper;
        }

        [HttpGet]
        [RateLimitFilterFactory(Order = 1, Limit = 20, PeriodInSec = 1 * 60 * 5, UserIdentifier = "ProfileId")]
        [LogWebRequestFilterFactory(Order = 2)]
        public async Task<IActionResult> Index()
        {
            var jobInfoModel = await _jobInfoService.GetByProfileIdAsync(User.ProfileId);

            var createJobInfoViewModel = _mapper.Map<CreateJobInfoViewModel>(jobInfoModel) ?? new CreateJobInfoViewModel();

            ViewBag.Jobs = (await _jobService.GetListAsync()).Select(x => new SelectListItem(x.Title, x.Id.ToString()));

            return View(createJobInfoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [RateLimitFilterFactory(Order = 1, Limit = 20, PeriodInSec = 1 * 60 * 5, UserIdentifier = "ProfileId")]
        [LogWebRequestFilterFactory(Order = 2)]
        public async Task<IActionResult> CreateAsync(CreateJobInfoViewModel jobInfoViewModel)
        {
            var joblist = (await _jobService.GetListAsync()).Select(x => new SelectListItem(x.Title, x.Id.ToString()));

            if (!ModelState.IsValid)
            {
                Alert(ModelState.ToErrorMessage(), NotificationType.Error);
                ViewBag.Jobs = joblist;
                return View("Index", jobInfoViewModel);
            }


            if (joblist.All(x => x.Value.ToLong() != jobInfoViewModel.JobId))
            {
                Alert("درخواست شما غیر مجاز است", NotificationType.Error);
                return RedirectToAction("Index");
            }

            if (jobInfoViewModel.JobId == 123159 && string.IsNullOrEmpty(jobInfoViewModel.JobDescription))
            {
                Alert("در صورت انتخاب شغل سایر، وارد کردن نام شغل اجباری می باشد.", NotificationType.Error);
                ViewBag.jobs = joblist;
                return View("Index", jobInfoViewModel);
            }

            if (jobInfoViewModel.JobId != 123159) jobInfoViewModel.JobDescription = null;

            var jobInfoModel = _mapper.Map<JobInfo>(jobInfoViewModel);

            var dbObject
                = await _jobInfoService.GetByProfileIdAsync(User.ProfileId);

            jobInfoModel.ProfileId = User.ProfileId;

            if (dbObject != null)
            {
                jobInfoModel.Id = dbObject.Id;
                jobInfoModel.CreationDate = dbObject.CreationDate;
                await _jobInfoService.UpdateAsync(jobInfoModel);
            }
            else
            {
                await _jobInfoService.CreateAsync(jobInfoModel);
            }


            return RedirectToNextStep(CurrentStep.JobInfo);
        }
    }
}

src/Web/Views/JobInfo/Index.cshtml
@using Cerberus.Utility
@model Cerberus.Web.ViewModel.JobInfo.CreateJobInfoViewModel
@{
    ViewBag.HeaderIconClass = "fa fa fa-briefcase";
    ViewBag.Title = "اطلاعات شغلی";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var jobsSelectList = ViewBag.Jobs as IEnumerable<SelectListItem>;

}
@await Html.PartialAsync("~/Views/Shared/_RealSteps.cshtml", 8)


<div class="form-wrapper">
    <form action="@Url.Action("CreateAsync","JobInfo")" method="post" id="form">
        @Html.AntiForgeryToken()
        <div class="form-steps">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.JobId):</label>
                        @Html.DropDownListFor(model => model.JobId, jobsSelectList, "شغل خود را انتخاب نمایید", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.JobId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label">@Html.DisplayNameFor(model => model.EmploymentDate):</label>
                        <span class="clearText" id="cleardate">پاک کردن</span>
                        @Html.TextBoxFor(model => model.EmploymentDate,
                            new
                            {
                                data_placement = "bottom",
                                data_format = "yyyy/MM/dd",
                                data_trigger = "focus",
                                @readonly = "readonly",
                                data_targetselector = "#EmploymentDate",
                                type = "text",
                                @class = "form-control text-center",
                                data_mddatetimepicker = "true"
                            })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 ">
                    <div class="form-group">
                        <label class="form-label">@Html.DisplayNameFor(model => model.CompanyName):</label>
                        @Html.TextBoxFor(model => model.CompanyName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label">@Html.DisplayNameFor(model => model.Position):</label>
                        @Html.TextBoxFor(model => model.Position, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-lg-12 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span>@Html.DisplayNameFor(model => model.CompanyAddress):</label>
                        @Html.TextBoxFor(model => model.CompanyAddress, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CompanyAddress, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.CompanyPhone):</label>
                        <div class="row mrg0L mrg0R">
                            <div class="col-md-9 col-xs-9 pad5L pad0R">
                                @Html.TextBoxFor(model => model.CompanyPhone, new { @class = "form-control is-ltr NumberInput", @maxlength = "8" })
                                @Html.ValidationMessageFor(model => model.CompanyPhone, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-3 col-xs-3 pad5L pad0R">
                                @Html.TextBoxFor(model => model.CompanyCityPrefix, new { @class = "form-control is-ltr NumberInput", @placeholder = "021", @maxlength = "3" })
                                @Html.ValidationMessageFor(model => model.CompanyCityPrefix, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label">@Html.DisplayNameFor(model => model.CompanyFax):</label>
                        <div class="row mrg0L mrg0R">
                            <div class="col-md-9 col-xs-9 pad5L pad0R">
                                @Html.TextBoxFor(model => model.CompanyFax, new { @class = "form-control is-ltr NumberInput", @maxlength = "8" })
                                @Html.ValidationMessageFor(model => model.CompanyFax, "", new { @class = "text-danger", @placeholder = "" })
                            </div>
                            <div class="col-md-3 col-xs-3 pad5L pad0R">
                                @Html.TextBoxFor(model => model.CompanyFaxPrefix, new { @class = "form-control is-ltr NumberInput", @placeholder = "021", @maxlength = "3" })
                                @Html.ValidationMessageFor(model => model.CompanyFaxPrefix, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.CompanyPostalCode):</label>
                        @Html.TextBoxFor(model => model.CompanyPostalCode, new { @class = "form-control is-ltr NumberInput", @maxlength = "10" })
                        @Html.ValidationMessageFor(model => model.CompanyPostalCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label">@Html.DisplayNameFor(model => model.CompanyWebSite):</label>
                        @Html.TextBoxFor(model => model.CompanyWebSite, new { @class = "form-control is-ltr font-eng", @placeholder = "http://csdiran.com" })
                        @Html.ValidationMessageFor(model => model.CompanyWebSite, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.CompanyEmail):</label>
                        @Html.TextBoxFor(model => model.CompanyEmail, new { @class = "form-control is-ltr font-eng", @placeholder = "example@csdiran.com" })
                        @Html.ValidationMessageFor(model => model.CompanyEmail, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6" id="descriptionJob">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.JobDescription):</label>
                        @Html.TextBoxFor(model => model.JobDescription, new { @class = "form-control", @placeholder = "شغل خود را در این قسمت درج نمایید" })
                        @Html.ValidationMessageFor(model => model.JobDescription, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="btn-wrapper text-left">
                <button type="submit"
                        class="btn btn-main" id="btnSubmit">
                    <i class="fa fa-check" aria-hidden="true"></i> تایید/ادامه مرحله بعد
                </button>
            </div>
        </div>
    </form>
    <div class="form-guide">
        <ul>
            <li>
                در صورت انتخاب شغلی که فاقد آدرس مشخص می باشد لطفا در فیلد آدرس شرکت/موسسه آدرس محل سکونت خود را وارد و همچنین در صورتیکه فاقد آدرس پست الکترونیکی شرکت/ موسسه می باشید از پست الکترونیکی شخصی استفاده نمایید.</li>
            <li>
                برای نحوه وارد کردن اطلاعات شغلی می توانید از<a href="" id="helpFile" style="color: red; text-decoration: underline; font-size: 14pt" data-toggle="modal" data-target="#jobModal"> راهنما </a> استفاده کنید.
            </li>
        </ul>
    </div>
</div>
<div class="modal fade" id="jobModal" role="dialog">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-center">راهنمای افزودن اطلاعات شغلی</h4>
            </div>
            <div class="modal-body" style="text-align: center">
                <img src="~/images/jobHelp.gif" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-block" data-dismiss="modal">بستن</button>
            </div>
        </div>

    </div>
</div>
<script>
    $(function () {
        $("#cleardate").click(function () {
            $("#EmploymentDate").val("");
        });
        if ($("#JobId").val() === "123159")
            $("#descriptionJob").removeClass("hidden");
        else
            $("#descriptionJob").addClass("hidden");


        $("#JobId").change(function () {
            if ($("#JobId").val() === "123159")
                $("#descriptionJob").removeClass("hidden");
            else
                $("#descriptionJob").addClass("hidden");
        })
    });
</script>