src/Web/Controllers/AuthenticationOfficesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Cerberus.Domain.Interface.Services;
using Cerberus.Domain.Model;
using Cerberus.Web.ViewModel.AuthenticationOffices;
using Cerberus.Web.WebLogic;
using Gatekeeper.AspModules.ActionFilter;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Cerberus.Web.Controllers
{
    public class AuthenticationOfficesController : BaseController
    {

        private readonly IAuthenticationOfficesService _authenticationOfficesService;
        private readonly IMapper _mapper;
        private readonly IProvinceService _provinceService;
        private readonly IBankService _bankService;

        public AuthenticationOfficesController(IAuthenticationOfficesService authenticationOfficesService,
            IMapper mapper,
           IProvinceService provinceService, IBankService bankService)
        {
            _authenticationOfficesService = authenticationOfficesService;
            _mapper = mapper;
            _provinceService = provinceService;
            _bankService = bankService;
        }


        [RateLimitFilterFactory(Order = 1, Limit = 500, PeriodInSec = 1 * 60 * 5)]
        public async Task<IActionResult> Index()
        {

            ViewBag.Provinces = (await _provinceService.GetListAsync()).Where(x => x.CountryId == 1).OrderBy(x => x.Name).Select(x => new SelectListItem(x.Name, x.Id.ToString()));
            ViewBag.Banks = (await _bankService.GetListForAuthenticationOfficeAsync()).OrderBy(x => x.Name).Select(x => new SelectListItem(x.Name, x.Id.ToString()));
            return View();
        }


        [RateLimitFilterFactory(Order = 1, Limit = 500, PeriodInSec = 1 * 60 * 5)]
        public async Task<PartialViewResult> Search(AuthenticationOfficesViewModel model)
        {
            if (!ModelState.IsValid)
               return PartialView(new List<AuthenticationOfficesViewModel>());

            var authenticationOffice = _mapper.Map<AuthenticationOffices>(model);
            var offices = await _authenticationOfficesService.GetListAsync(authenticationOffice, model.PageNumber * 20, 20);
            ViewBag.paging = DivideRoundingUp(offices.recordCount, 20);
            ViewBag.page = model.PageNumber;
            ViewBag.recordCount = offices.recordCount;
            var viewModel = _mapper.Map<List<AuthenticationOffices>, List<AuthenticationOfficesViewModel>>(offices.authenticationOfficeses);
            return PartialView(viewModel);
        }

        [RateLimitFilterFactory(Order = 1, Limit = 500, PeriodInSec = 1 * 60 * 5)]
        public async Task<PartialViewResult> NotInPresenceSearch(AuthenticationOfficesViewModel model)
        {
            if (!ModelState.IsValid)
                return PartialView(new List<AuthenticationOfficesViewModel>());

            var authenticationOffice = _mapper.Map<AuthenticationOffices>(model);
            var offices = await _authenticationOfficesService.GetListAsync(authenticationOffice, 0, 20);
            var viewModel = _mapper.Map<List<AuthenticationOffices>, List<AuthenticationOfficesViewModel>>(offices.authenticationOfficeses);
            return PartialView(viewModel);
        }
        public long DivideRoundingUp(long x, long y) => Math.DivRem(x, y, out var remainder);
    }
}

src/Web/Views/AuthenticationOffices/Index.cshtml
@model Cerberus.Web.ViewModel.AuthenticationOffices.AuthenticationOfficesViewModel
@using static Cerberus.Utility.Tools
@{
    ViewData["Title"] = "لیست مراکز منتخب احراز هویت";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var provinceSelectList = ViewBag.Provinces as IEnumerable<SelectListItem> ?? new List<SelectListItem>();
    var bankSelectList = ViewBag.Banks as IEnumerable<SelectListItem> ?? new List<SelectListItem>();
    var defaultCity = new List<SelectListItem>();
}






<div class="form-wrapper">
    <h3 tabindex="-1" class="title-form">
        <i>
            <i class="fa fa-credit-card" aria-hidden="true"></i>
        </i>
        <span>لیست مراکز منتخب احراز هویت</span>
    </h3>

    <form action="@Url.Action("Search","AuthenticationOffices")" method="post" id="frmSearch">
        @Html.AntiForgeryToken()

        <div class="form-steps">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="form-group dr-form-group">
                        <label class="form-label">نوع احراز هویت</label>
                        <span class="form-select">

                            @Html.DropDownListFor(model => model.AuthType, ToSelectList<Cerberus.Domain.Enum.AuthenticationOfficesType>().Skip(3).Take(2)
                                                                                                                                         .OrderByDescending(x => x.Value), new { @class = "form-control" })

                        </span>
                        @Html.ValidationMessageFor(model => model.Type, "", new { id = "AuthType", @class = "text-danger", })

                    </div>
                </div>
            </div>
            <div id="presenceFrame">
                <div class="row">
                    <div class="col-md-3 col-sm-6" id="officeTypeFrame">
                        <div class="form-group dr-form-group">
                            <label class="form-label">نوع دفتر</label>
                            <span class="form-select">

                                @Html.DropDownListFor(model => model.Type, ToSelectList<Cerberus.Domain.Enum.AuthenticationOfficesType>().Where(x => x.Value != ((byte)Cerberus.Domain.Enum.AuthenticationOfficesType.Presence).ToString() && x.Value != ((byte)Cerberus.Domain.Enum.AuthenticationOfficesType.NotInPresence).ToString())
                                                                                                                                          .OrderBy(x => x.Value == "1" ? "4" : x.Value =="2" ? "1" : x.Value == "3" ? "2" : "3"), "-", new { @class = "form-control" })

                            </span>
                            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger", })

                        </div>
                    </div>
                    <div class="col-md-3 col-sm-12 hidden" id="bankFrame">
                        <div class="form-group dr-form-group">
                            <label class="form-label">@Html.DisplayNameFor(model => model.BankId)</label>
                            @Html.DropDownListFor(model => model.BankId, bankSelectList, "انتخاب بانک..", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.BankId, "", new { @class = "text-danger" })
                        </div>
                    </div>
            

                    <div class="col-md-3 col-sm-12">
                        <div class="form-group dr-form-group">
                            <label class="form-label">استان</label>

                            @Html.DropDownListFor(x => x.ProvinceId, provinceSelectList, "انتخاب استان ...", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ProvinceId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-12">
                        <div class="form-group dr-form-group">
                            <label class="form-label">شهر</label>
                            @Html.DropDownListFor(x => x.CityId, defaultCity, "انتخاب شهر ...", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })

                        </div>
                    </div>


                </div>
                <div class="row">
                    <div class="col-md-3 col-sm-12" id="officeNameFrame">
                        <div class="form-group">
                            <label class="form-label">نام مرکز احراز هویت</label>
                            @Html.TextBoxFor(x => x.OfficeName, null, new { id = "OfficeName", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.OfficeName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="form-group">
                            <label class="form-label">آدرس</label>
                            @Html.TextBoxFor(x => x.Address, null, new { id = "Address", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="btn-wrapper">
            <button type="submit" class="btn btn-main" id="submitBtn"><i class="glyphicon glyphicon-search" aria-hidden="true"></i> جستجو </button>
        </div>
        <div class="row text-center" style="margin-top: 15px" id="description">
            <span style="font-size: 12pt">
                لیست زیر شامل دفاتر منتخب پیشخوان دولت و کارگزاری های منتخب جهت احراز هویت می باشد.ضمنا اعلام می گردد هزینه احراز هویت در دفاتر پیشخوان دولت برای شخص اصیل <span style="font-weight: bold; text-decoration: underline; color: red">111.000 ریال</span> و برای نماینده قانونی <span style="font-weight: bold; text-decoration: underline; color: red">127.000 ریال</span> است
            </span>
        </div>
    </form>
    <div id="content" style="margin-top: 20px">

    </div>
</div>

<script>

     $("#Type").change(function () {
        if ($("#Type").val() == '3') {
            $("#bankFrame").removeClass('hidden');
        }
        else {
            $("#bankFrame").addClass('hidden');
            $("#BankId").val('');
        }
    });

     $("#AuthType").change(function () {
     if ($("#AuthType").val() == '4') {
             $("#presenceFrame").addClass('hidden');
             $("#description").addClass('hidden');
         }
         else{
            $("#presenceFrame").removeClass('hidden');
            $("#description").removeClass('hidden');
             $("#Type").val('');

         }
     });
    $("#AuthType").load(function () {
     if ($("#AuthType").val() == '4') {
             $("#presenceFrame").addClass('hidden');
             $("#description").addClass('hidden');
         }
         else{
            $("#presenceFrame").removeClass('hidden');
            $("#description").removeClass('hidden');

         }
    });

    $(function () {
    $("#submitBtn").click(function (event) {
            event.preventDefault();
            getPost(0);
        });

    });
   

    function getPost(id) {
        $("#myModal").modal('show');

        var type = $('#Type').val();
        var cityId = $('#CityId').val();
        var provinceId = $('#ProvinceId').val();
        var address = $('#Address').val();
        var officeName = $('#OfficeName').val();
        var bankId = $('#BankId').val();
        if ($('#AuthType').val() == 4) {
            type = 4;
            cityId = null;
            provinceId = null;
            address = null;
            officeName = "";
            bankId = null;
        }
        var model = {
            "provinceId": provinceId, "cityId": cityId, "type": type, "address": address, "officeName": officeName, "BankId": bankId, "pageNumber": id
        };

        var dataUrl = '@Url.Action("Search","AuthenticationOffices")';
        if (type == 4) {
            var dataUrl = '@Url.Action("NotInPresenceSearch","AuthenticationOffices")';
        }


        $.ajax({
            type: "POST",
            url: dataUrl,
            data: model,
            // contentType: "application/json",
            success: function (result) {
                $("#content").html(result);
                $("#myModal").modal('hide');
            },
            error: function () {
                $("#myModal").modal('hide');
                swal({
                    title: "توجه",
                    text: "خطایی رخ داده، لطفا چند دقیقه دیگر امتحان نمایید",
                    type: 'warning',
                    showConfirmButton: true,
                    confirmButtonText: 'متوجه شدم',
                    timer: 5000
                });

            }

        });



    }

    $("#ProvinceId").change(function () {
        $("#myModal").modal("show");
        var $select = $('#CityId');
        if ($('#ProvinceId').val() !== "") {
            $.ajax({
                url: '/api/cities/' + $("#ProvinceId").val(),
                contentType: "application/json",
                success: function(results) {

                    if (results.length > 0) {
                        $.each(results,
                            function() {

                                $select.find('option').remove();
                            $select.append('<option value= '+'@null'+' >همه شهرها</option>');
                                $.each(results,
                                    function(key, value) {
                                        $select.append('<option value=' + value.value + '>' + value.text + '</option>');
                                    });
                            });
                       }
                    $("#myModal").modal("hide");
                },

            });
        } else {
            $select.find('option').remove();
            $("#myModal").modal("hide");
        }

    });

</script>

src/Web/Views/AuthenticationOffices/NotInPresenceSearch.cshtml
@using Cerberus.Utility
@model List<Cerberus.Web.ViewModel.AuthenticationOffices.AuthenticationOfficesViewModel>


@if (Model.Any())
{
    int rowNumber = 1;
    <div id="content">

        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-responsive" id="dataTables-example">
                <thead>
                <tr class="text-center">
                    <th class="text-center  ">
                        ردیف
                    </th>
                    <th class="text-center  ">
                        نام
                    </th>
                    <th class="text-center   ">
                        دانلود
                    </th>
                    <th class="text-center  ">
                        شماره تماس پشتیبانی
                    </th>    
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr class="odd  text-center">
                        <td class="text-center  ">
                            @(rowNumber++)
                        </td>
                        <td class="text-center  ">
                            @item.ResponsibleName
                        </td>
                        <td class="text-center ">
                            <a href="@item.Address" target="_blank">لینک</a>
                        </td>                      
                        <td>
                            @item.Telephone
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
  
    </div>
}

src/Web/Views/AuthenticationOffices/Search.cshtml
@using Cerberus.Utility
@model List<Cerberus.Web.ViewModel.AuthenticationOffices.AuthenticationOfficesViewModel>


@if (Model.Any())
{
    int rowNumber = (ViewBag.page * 20) + 1;
    <div id="content">

        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-responsive" id="dataTables-example">
                <thead>
                <tr class="text-center">
                    <th class="text-center  ">
                        ردیف
                    </th>
                    <th class="text-center  ">
                        استان
                    </th>
                    <th class="text-center   ">
                        شهر
                    </th>
                    <th class="text-center  ">
                        نوع دفتر
                    </th>    
               
                    <th class="text-center">
                        تلفن
                    </th>
                    <th class="text-center">
                        آدرس
                    </th>
                    <th class="text-center  ">
                        مسئول
                    </th>
                    <th class="text-center  ">
                        نام مرکز احراز هویت
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr class="odd  text-center">
                        <td class="text-center  ">
                            @(rowNumber++)
                        </td>
                        <td class="text-center  ">
                            @item.ProvinceId
                        </td>
                        <td class="text-center ">
                            @item.CityId
                        </td>
                        <td class="text-center ">
                            @(item.BankId != null? ($"{item.Type.GetEnumDescription()} - { @item.Bank.Name}"): (item.Type.GetEnumDescription()))
                        </td>
                     
                      
                        <td>
                            @item.Telephone
                        </td>
                        <td>
                            @item.Address
                        </td>
                        <td class="text-center ">
                            @item.ResponsibleName
                        </td>
                        <td class="text-center ">
                            @item.OfficeName
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
        <div class="dir-ltr">
            <nav aria-label="Page navigation example" class="text-center">
                <ul class="pagination">
                    @{
                        var range = 3;
                        var renderBeforCurrent = false;
                        var renderAfterCurrent = false;
                    }
                    @if (ViewBag.page >= 0)
                    {
                        if (ViewBag.paging >= 1)
                        {
                            <li class="@(ViewBag.page == 0 ? "active" : "") ">
                                <a onclick="getPost('0')">1</a>
                            </li>
                        }

                    }
                    @for (long i = 1; i <= ViewBag.paging - 1; i++)
                    {
                        if (Math.Abs(i - ViewBag.page) < range)
                        {
                            <li class="@(ViewBag.page == i ? "active" : "")  ">
                                <a onclick="getPost('@i')">@(i + 1)</a>
                            </li>
                        }
                        else if (!renderBeforCurrent && ViewBag.page > i)
                        {
                            renderBeforCurrent = true;
                            <li>
                                <a>..</a>
                            </li>
                        }
                        else if (!renderAfterCurrent && ViewBag.page < i)
                        {
                            renderAfterCurrent = true;
                            <li>
                                <a>..</a>
                            </li>
                        }
                    }
                    <li class="@(ViewBag.page == ViewBag.paging ? "active" : "")  ">
                        <a onclick="getPost('@ViewBag.paging')">@(ViewBag.paging + 1)</a>
                    </li>
                </ul>
            </nav>
        </div>
        <span style="font-weight: bold">تعداد رکورد یافت شده :@ViewBag.recordCount</span>


    </div>
}