src/Web/Controllers/BankingAccountController.cs
using System;
using AutoMapper;
using Cerberus.Domain.Interface.Services;
using Cerberus.Domain.Model;
using Cerberus.Web.Enum;
using Cerberus.Web.Extensions;
using Cerberus.Web.Filters;
using Cerberus.Web.ViewModel.BankingAccount;
using Cerberus.Web.WebLogic;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cerberus.Domain.Enum;
using Cerberus.Domain.Extensions;
using Cerberus.Domain.Interface.Inquiries;
using Cerberus.Domain.Interface.Services.Membership;
using Cerberus.Domain.Model.Membership;
using Cerberus.Utility;
using Gatekeeper.AspModules.ActionFilter;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Cerberus.Web.Controllers
{

    public class BankingAccountController : BaseController
    {
        private readonly IProfileService _profileService;
        private readonly IBankingAccountService _bankingAccountService;
        private readonly IBankService _bankService;
        private readonly ICityService _cityService;
        private readonly IMapper _mapper;
        private readonly IProvinceService _provinceService;
        private readonly IMembershipService _membershipService;
        private readonly IProfilePackageService _profilePackageService;
        private readonly IOfflineTaskService _offlineTaskService;
        private readonly IProfileHistoryService _profileHistoryService;
        public BankingAccountController(
               IProfileService profileService,
               IBankingAccountService bankingAccountService,
               IBankService bankService,
               ICityService cityService,
               IMapper mapper,
               IProvinceService provinceService,
               IMembershipService membershipService,
               IProfilePackageService profilePackageService,
               IOfflineTaskService offlineTaskService, IProfileHistoryService profileHistoryService)
        {
            _profileService = profileService;
            _bankingAccountService = bankingAccountService;
            _bankService = bankService;
            _cityService = cityService;
            _mapper = mapper;
            _provinceService = provinceService;
            _membershipService = membershipService;
            _profilePackageService = profilePackageService;
            _offlineTaskService = offlineTaskService;
            _profileHistoryService = profileHistoryService;
        }

        [HttpGet]
        [Route("bankingAccounts")]
        [AuthorizeUserFilterFactory(Scope = (int)(AvailableScope.BankingAccount))]
        [RateLimitFilterFactory(Order = 1, Limit = 30, PeriodInSec = 1 * 60 * 5, UserIdentifier = "ProfileId")]
        [LogWebRequestFilterFactory(Order = 2)]
        public async Task<IActionResult> Index()
        {
            ViewBag.CanEdit = false;

            // Remove TempData
            if (TempData["dashboard"] as string == "ok") TempData.Remove("dashboard");


            var user = await _profileService.GetAsync(User.ProfileId);

            if (user.Status < ProfileStatus.PolicyAccepted)
                if (User.ServiceId.HasValue && User.ServiceId.Value > 0)
                {
                    var membership =
                        await _membershipService.GetPrivatePersonAsync(user.UniqueIdentifier, user.Mobile.ToString(), User.ServiceId.Value);

                    ViewBag.CanEdit = membership?.CanEditAccounts ?? false;
                }



            ViewBag.Provinces = (await _provinceService.GetListAsync()).Where(x => x.CountryId == 1).OrderBy(x => x.Name).Select(x => new SelectListItem(x.Name, x.Id.ToString()));
            ViewBag.Banks = (await _bankService.GetListAsync()).OrderBy(x => x.Name).Select(x => new SelectListItem(x.Name, x.Id.ToString()));


            var bankingAccounts = await _bankingAccountService.GetListAsync(User.ProfileId, true);
            var allAccounts = bankingAccounts as BankingAccount[] ?? bankingAccounts.ToArray();





            if (allAccounts.Any())
            {
                var createBankingAccountViewModel = new CreateBankingAccountViewModel
                {
                    BankingAccounts = allAccounts
                };
                return View(createBankingAccountViewModel);
            }


            if (User.ServiceId.HasValue && User?.ServiceId.Value > 0 && user.Status < ProfileStatus.PolicyAccepted)
            {
                var checkUser = await _membershipService.GetPrivatePersonAsync(user.UniqueIdentifier, user.Mobile.ToString(), User.ServiceId.Value);

                if (checkUser != null)
                {
                    var bankingAccountTmp = (await _membershipService.GetAccountAsync(user.UniqueIdentifier, User.ServiceId.Value));
                    if (bankingAccountTmp != null)
                    {

                        var bankingAccount = _mapper.Map<CreateBankingAccountViewModel>(bankingAccountTmp);

                        var bankingAccountViewModel = new CreateBankingAccountViewModel
                        {
                            AccountNumber = bankingAccount.AccountNumber,
                            IsDefault = bankingAccount.IsDefault,
                            Type = bankingAccount?.Type,
                            BankId = bankingAccount?.BankId,
                            BranchCityId = bankingAccount?.BranchCityId,
                            BranchCode = bankingAccount?.BranchCode,
                            BranchName = bankingAccount?.BranchName,
                            Sheba = bankingAccount?.Sheba,
                            BankingAccounts = new List<BankingAccount>(),
                            LockAccount = checkUser.CanEditAccounts
                        };
                        if (ViewBag.CanEdit == true)
                        {
                            Alert("به دلیل استفاده از لینک تخفیف ، شما نمی توانید شبا بانکی خود را تغییر دهید", NotificationType.Error);
                        }
                        return View(bankingAccountViewModel);
                    }
                }

            }

            var accountViewModel = new CreateBankingAccountViewModel
            {
                BankingAccounts = new List<BankingAccount>()
            };

            return View(accountViewModel);

        }

        [HttpGet]
        [AuthorizeUserFilterFactory]
        //  [Route("bankingAccounts/nextStep")]
        public async Task<IActionResult> Redirect()
        {

            var accounts = await _bankingAccountService.GetListAsync(User.ProfileId);
            var bankingAccounts = accounts as BankingAccount[] ?? accounts.ToArray();
            if (!bankingAccounts.Any())
            {
                Alert("ثبت حداقل یک شماره حساب پیش فرض برای ادامه ثبت نام/ویرایش اجباری است.", NotificationType.Warning);
                if (Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.BankingAccount))

                    return RedirectToAction("Index");

                return RedirectToAction("Edit");
            }

            if (!bankingAccounts.Any(x => x.IsDefault))
            {
                Alert("تعیین یک حساب پیشفرض الزامی می باشد .", NotificationType.Warning);
                return RedirectToAction(Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.BankingAccount)
                    ? "Index"
                    : "Edit");
            }
            var profile = await _profileService.GetAsync(User.ProfileId);
            if (profile.IsEditBankingAccountSemiSejami() || profile.IsEditPrivatePersonSemiSejami() || profile.IsEditBankingAccountAndDeleteAgentEighteen() || profile.IsEditPrivatePersonAndDeleteAgentEighteen())
            {
                var package = await _profilePackageService.GetUnusedPackagesAsync(profile.Id, PackageType.EditAllData, PackageUsedFlag.EditBankingAccount);
                if (package != null)
                {
                    if (profile.Status == ProfileStatus.SemiSejami && profile.StatusReasonType == StatusReasonType.EditBankingAccount && bankingAccounts.All(x => x.IsConfirmed == true))
                    {

                        await _profileHistoryService.CreateAsync(new ProfileHistory
                        {
                            ReferenceId = ProfileHistoryReferenceType.UpdateBankingAccount.ToString(),
                            ProfileId = User.ProfileId,
                        }, ProfileStatus.Sejami);

                        profile.Status = ProfileStatus.Sejami;
                        profile.StatusReasonType = null;
                        await _profileService.UpdateStatusAndReasonAsync(profile);

                        return RedirectToAction("Index", "Dashboard");
                    }
                    if (bankingAccounts.All(x => x.IsConfirmed == true))
                    {
                        return RedirectToAction("Index", "Dashboard");
                    }
                    if (bankingAccounts.Any(x => x.IsConfirmed == null))
                    {

                        await _offlineTaskService.ScheduleEditAfterSejamiTasksAsync(profile.Id);
                        return View("FinalEdit", package);
                    }

                    Alert("شما اطلاعات بانکی خود را ویرایش ننموده اید", NotificationType.Warning);
                    return RedirectToAction(nameof(Edit));
                }

                Alert("برای عملیات ویرایش باید عملیات پرداخت را انجام دهید", NotificationType.Warning);
                return RedirectToAction(nameof(Edit));

            }
            return RedirectToNextStep(CurrentStep.BankingAccount);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("bankingAccounts")]
        [AuthorizeUserFilterFactory(Scope = (int)(AvailableScope.BankingAccount))]
        [RateLimitFilterFactory(Order = 1, Limit = 20, PeriodInSec = 1 * 60 * 5, UserIdentifier = "ProfileId")]
        [LogWebRequestFilterFactory(Order = 2)]

src/Web/Controllers/FinancialInfoController.cs
using System;
using AutoMapper;
using Cerberus.Domain.Interface.Services;
using Cerberus.Domain.Model;
using Cerberus.Web.Enum;
using Cerberus.Web.Extensions;
using Cerberus.Web.Filters;
using Cerberus.Web.ViewModel.FinancialInfo;
using Cerberus.Web.WebLogic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cerberus.Domain.Enum;
using Cerberus.Utility;
using Gatekeeper.AspModules.ActionFilter;

namespace Cerberus.Web.Controllers
{
    [AuthorizeUserFilterFactory(Scope = (int)AvailableScope.FinancialInfo)]
    public class FinancialInfoController : BaseController
    {
        private readonly IFinancialInfoService _financialInfoService;
        private readonly IMapper _mapper;
        private readonly IBrokerService _brokerService;

        public FinancialInfoController(IFinancialInfoService financialInfoService, IMapper mapper, IBrokerService brokerService)
        {
            _financialInfoService = financialInfoService;
            _mapper = mapper;
            _brokerService = brokerService;
        }

        [HttpGet]
        [RateLimitFilterFactory(Order = 1, Limit = 20, PeriodInSec = 1 * 60 * 5, UserIdentifier = "ProfileId")]
        [LogWebRequestFilterFactory(Order = 2)]
        public async Task<IActionResult> Index()
        {
            var financialInfoModel = await _financialInfoService.GetByProfileIdAsync(User.ProfileId, true);

            var createFinancialInfoViewModel = _mapper.Map<FinancialInfo, CreateFinancialInfoViewModel>(financialInfoModel) ?? new CreateFinancialInfoViewModel();
            createFinancialInfoViewModel.ProfileOwnerType = User.ProfileOwnerType;
            ViewBag.Brokers = (await _brokerService.GetListAsync()).OrderBy(x => x.Title).Select(x => new SelectListItem(x.Title, x.Id.ToString()));

            if (financialInfoModel?.FinancialBrokers != null)
                createFinancialInfoViewModel.BrokerIds = financialInfoModel.FinancialBrokers.Select(x => x.BrokerId);

            return View(createFinancialInfoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [RateLimitFilterFactory(Order = 1, Limit = 20, PeriodInSec = 1 * 60 * 5, UserIdentifier = "ProfileId")]
        [LogWebRequestFilterFactory(Order = 2)]
        public async Task<IActionResult> CreateAsync(CreateFinancialInfoViewModel financialInfoViewModel)
        {

            if (!ModelState.IsValid)
            {
                Alert("مقادیر ورودی نامعتبر می باشد", NotificationType.Error);
                return RedirectToAction(nameof(Index));
            }

            if ((User.ProfileOwnerType == ProfileOwnerType.ForeignPrivatePerson || User.ProfileOwnerType == ProfileOwnerType.IranianPrivatePerson) && financialInfoViewModel.TradingKnowledgeLevel == null)
            {
                Alert("میزان آشنایی شما با مفاهیم مالی و سرمایه گذاری اجباری است.", NotificationType.Error);
                return RedirectToAction(nameof(Index));
            }
            if ((User.ProfileOwnerType == ProfileOwnerType.ForeignLegalPerson || User.ProfileOwnerType == ProfileOwnerType.IranianLegalPerson) && financialInfoViewModel.CheckRate == 1)
            {
                if (financialInfoViewModel.Rate == null ||
                    string.IsNullOrWhiteSpace(financialInfoViewModel.ReferenceRateCompany) ||
                    string.IsNullOrWhiteSpace(financialInfoViewModel.RateDate))
                {
                    Alert(
                        "در صورتی که مشتری از طرف مرجعی مورد رتبه بندی قرار گرفته باشد، نام مرجع رتبه بندی، تاریخ رتبه بندی و رتبه اخذ شده اجباری می باشد",
                        NotificationType.Error);
                    return RedirectToAction(nameof(Index));
                }
            }

            var brokers = new List<Broker>();

            if (financialInfoViewModel.BrokerIds != null && financialInfoViewModel.BrokerIds.Count() != 0)
            {
                foreach (var brokerId in financialInfoViewModel.BrokerIds)
                {
                    var broker = await _brokerService.GetAsync(brokerId);
                    if (broker != null)
                        brokers.Add(broker);
                    else
                    {
                        ModelState.AddModelError(nameof(financialInfoViewModel.BrokerIds), "کارگزار انتخاب شده در سجام تعریف نشده است");
                        return View("Index", financialInfoViewModel);
                    }
                }
            }

            var financialInfoModel = _mapper.Map<FinancialInfo>(financialInfoViewModel);

            var dbObject = await _financialInfoService.GetByProfileIdAsync(User.ProfileId);

            financialInfoModel.ProfileId = User.ProfileId;

            if (dbObject != null)
            {
                financialInfoModel.Id = dbObject.Id;
                financialInfoModel.CreationDate = dbObject.CreationDate;
                await _financialInfoService.UpdateAsync(financialInfoModel, brokers);
            }
            else
            {
                await _financialInfoService.CreateAsync(financialInfoModel, brokers);
            }


            return RedirectToNextStep(CurrentStep.FinancialInfo);
        }
    }
}

src/Web/Views/Shared/_CaptchaControl.cshtml
<script>
  
    function resetCaptchaImage() {
       var d = new Date();
       $("#img-captcha").attr("src", "/session/getcaptchaimage?" + d.getTime());
    }
</script>
 <div class="form-group">
     <div>
         <img id="img-captcha" onclick="resetCaptchaImage()" src="~/session/getCaptchaImage" alt="بروز رسانی"  style="width: 100%;height:50px"/>
     </div>
     <div>
         <span class="form-hint">(کلیک بر روی تصویر جهت بروزرسانی)</span>
     </div>
     <div>
         <input type="text" name="CaptchaCode" class="form-control" placeholder="کد امنیتی را وارد کنید" maxlength="6"  autocomplete="off"/>
     </div>
     
 </div>
        
    

src/Web/Views/Shared/_LegalPersonStep.cshtml
@using Cerberus.Web.Enum
@using Cerberus.Web.Extensions
@model int
@{
    var canEditPayment = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.Payment);
    var canEditBaseInfo = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.BaseInfo);
    var canEditAddress = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.Address);
    var canEditTradingCode = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.TradingCode);
    var canEditTakeAccess = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.StakeholderTakeAccess);
    var canEditTakeManager = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.StakeholderTakeManager);
    var canEditShareHolder = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.StakeholderShareholder);
    var canEditTakeOrder = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.StakeholderTakeOrder);
    var canEditFinancialInfo = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.FinancialInfo);
    var canEditBankingAccount = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.BankingAccount);
    var canEditConfirm = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.Confirm);

}
<section class="content-header">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:;">سجام</a></li>
        <li class="breadcrumb-item active"> @ViewBag.Title</li>
    </ol>
    <h1>
        @if (ViewBag.HeaderIconClass != null)
        {
            <i class="@ViewBag.HeaderIconClass"></i>
        }
        @ViewBag.Title
    </h1>
</section>
<div class="steps-wrapper hideallsteps">
    <div class="steps clearfix">
        <ul role="tablist">
            <li role="tab" class="done" aria-disabled="false" aria-selected="true">
                <a href="javascript:;">
                    <span class="current-info audible">مرحله: </span>
                    <i>
                        <i class="fa fa-registered" aria-hidden="true"></i>
                    </i>
                    <span>ثبت نام</span>
                </a>
            </li>
            <li role="tab" class="done" aria-disabled="true">
                <a href="javascript:;">
                    <i>
                        <i class="fa fa-question" aria-hidden="true"></i>
                    </i>
                    <span>کد تایید / نوع مشتری</span>
                </a>
            </li>

            <li role="tab" class="@(Model == 3 ? "current" : "disabled" ) @(Model>3?"done":"")" aria-disabled="true">
                <a href="@(canEditPayment?@Url.Action("Index","Payment"):"#")">
                    <i>
                        <i class="fa fa-money" aria-hidden="true"></i>
                    </i>
                    <span>پرداخت</span>
                </a>
            </li>

            <li role="tab" class="@(Model == 4 ? "current" : "disabled" ) @(Model>4?"done":"")" aria-disabled="true">
                <a href="@(canEditBaseInfo?@Url.Action("Index","BaseInfo"):"#")">
                    <i>
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </i>
                    <span> شخص حقوقی</span>
                </a>
            </li>
            <li role="tab" class="@(Model == 5 ? "current" : "disabled" ) @(Model>5?"done":"")" aria-disabled="true">
                <a href="@(canEditAddress?@Url.Action("Index","Address"):"#")">
                    <i>
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </i>
                    <span> اطلاعات ارتباطی</span>
                </a>
            </li>
            <li role="tab" class="@(Model == 6 ? "current" : "disabled" ) @(Model>6?"done":"")" aria-disabled="true">
                <a href="@(canEditTradingCode?@Url.Action("Index","TradingCode"):"#")">
                    <i>
                        <i class="fa fa-list-alt" aria-hidden="true"></i>
                    </i>
                    <span>کدهای معاملاتی</span>
                </a>
            </li>
            <li role="tab" class="@(Model == 7 ? "current" : "disabled" ) @(Model>7?"done":"")" aria-disabled="true">
                <a href="@(canEditTakeAccess?@Url.Action("TakeAccess","Stakeholder"):"#")">
                    <i>
                        <i class="fa fa-id-card-o" aria-hidden="true"></i>
                    </i>
                    <span> دارندگان حق برداشت</span>
                </a>
            </li>
            <li role="tab" class="@(Model == 8 ? "current" : "disabled" ) @(Model>8?"done":"")" aria-disabled="true">
                <a href="@(canEditTakeManager?Url.Action("Manager","Stakeholder"):"#")">
                    <i>
                        <i class="fa fa-sitemap" aria-hidden="true"></i>
                    </i>
                    <span> هیئت مدیره</span>
                </a>
            </li>
            <li role="tab" class="@(Model == 9 ? "current" : "disabled" ) @(Model>9?"done":"")" aria-disabled="true">
                <a href="@(canEditShareHolder?Url.Action("Shareholder","Stakeholder"):"#")">
                    <i>
                        <i class="fa fa-handshake-o" aria-hidden="true"></i>
                    </i>
                    <span> سهامداران</span>
                </a>
            </li>
            <li role="tab" class="@(Model == 10 ? "current" : "disabled" ) @(Model>10?"done":"")" aria-disabled="true">
                <a href="@(canEditTakeOrder?@Url.Action("OrderAccess","Stakeholder"):"#")">
                    <i>
                        <i class="fa fa-users" aria-hidden="true"></i>
                    </i>
                    <span> اشخاص مجاز به سفارش</span>
                </a>
            </li>
            <li role="tab" class="@(Model == 11 ? "current" : "disabled" ) @(Model>11?"done":"")" aria-disabled="true">
                <a href="@(canEditFinancialInfo?@Url.Action("Index","FinancialInfo"):"#")">
                    <i>
                        <i class="fa fa-fort-awesome" aria-hidden="true"></i>
                    </i>
                    <span>اهداف سرمایه گذاری</span>
                </a>
            </li>
            <li role="tab" class="@(Model == 12 ? "current" : "disabled" ) @(Model>12?"done":"")" aria-disabled="true">
                <a href="@(canEditBankingAccount?@Url.Action("Index","BankingAccount"):"#")">
                    <i>
                        <i class="fa fa-credit-card" aria-hidden="true"></i>
                    </i>
                    <span> حساب بانکی</span>
                </a>
            </li>
            <li role="tab" class="@(Model == 13 ? "current" : "disabled") @(Model>13?"done":"")" aria-disabled="true">
                <a href="@(canEditConfirm?@Url.Action("Index","Confirm"):"#")">
                    <i>
                        <i class="fa fa-id-badge" aria-hidden="true"></i>
                    </i>
                    <span>تعهدات</span>
                </a>
            </li>
        </ul>
    </div>
</div>

src/Web/Views/Shared/_RealSteps.cshtml
@using Cerberus.Web.Enum
@using Cerberus.Web.Extensions
@model int
@{
    var canEditAgent = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.Agent);
    var canEditPayment = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.Payment);
    var canEditBaseInfo = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.BaseInfo);
    var canEditAddress = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.Address);
    var canEditTradingCode = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.TradingCode);
    var canEditJobInfo = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.JobInfo);
    var canEditFinancialInfo = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.FinancialInfo);
    var canEditBankingAccount = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.BankingAccount);
    var canEditConfirm = Context.Request.GetCurrentUserData().AvailableScope.HasFlag(AvailableScope.Confirm);

}
<section class="content-header">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:;">سجام</a></li>
        <li class="breadcrumb-item active"> @ViewBag.Title</li>
    </ol>
    <h1>
        @if (ViewBag.HeaderIconClass != null)
        {
            <i class="@ViewBag.HeaderIconClass"></i>
        }
        @ViewBag.Title
    </h1>
</section>

<div class="steps-wrapper hideallsteps mb-2">
    <div class="steps clearfix">
        <ul role="tablist">
            <li role="tab" class="first @(Model==1?"current":"done") " aria-disabled="false" aria-selected="true">
                <a href="javascript:;">
                    <span class="current-info audible">مرحله: </span>
                    <i>
                        <i class="fa fa-registered" aria-hidden="true"></i>
                    </i>
                    <span>ثبت نام</span>
                </a>
            </li>
            <li role="tab" class="@(Model == 2 ? "current" : "disabled" ) @(Model>2?"done":"")" aria-disabled="true">
                <a href="javascript:;">
                    <i>
                        <i class="fa fa-question" aria-hidden="true"></i>
                    </i>
                    <span>کد تایید/ نوع مشتری</span>
                </a>
            </li>

     
            <li role="tab" class="@(Model==3?"current":"disabled") @(Model>3?"done":"")" aria-disabled="true">
                <a href="@(canEditPayment? @Url.Action("Index","Payment") : "#")">
                    <i>
                        <i class="fa fa-money" aria-hidden="true"></i>
                    </i>
                    <span>پرداخت</span>
                </a>
            </li>
            <li role="tab" class="@(Model==4?"current":"disabled") @(Model>4?"done":"")" aria-disabled="true">
                <a href="@(canEditBaseInfo ? @Url.Action("Index","BaseInfo") : "#")">
                    <i>
                        <i class="fa fa-male" aria-hidden="true"></i>
                    </i>
                    <span>اطلاعات هویتی</span>
                </a>
            </li>
            <li role="tab" class="@(Model==5?"current":"disabled") @(Model>5?"done":"")" aria-disabled="true">
                <a href="@(canEditAgent? @Url.Action("Index","Agent"): "#")">
                    <i>
                        <i class="fa fa-bookmark" aria-hidden="true"></i>
                    </i>
                    <span>سمت و شرایط نماینده</span>
                </a>
            </li>
            <li role="tab" class="@(Model==6?"current":"disabled") @(Model>6?"done":"")" aria-disabled="true">
                <a href="@(canEditAddress?@Url.Action("Index","Address"):"#")">
                    <i>
                        <i class="fa fa-graduation-cap" aria-hidden="true"></i>
                    </i>
                    <span>اطلاعات ارتباطی</span>
                </a>
            </li>
            <li role="tab" class="@(Model==7?"current":"disabled") @(Model>7?"done":"")" aria-disabled="true">
                <a href="@(canEditTradingCode?@Url.Action("Index","TradingCode"):"#")">
                    <i>
                        <i class="fa fa-list-alt" aria-hidden="true"></i>
                    </i>
                    <span>کد های سهامداری</span>
                </a>
            </li>
            <li role="tab" class="@(Model==8?"current":"disabled") @(Model>8?"done":"")" aria-disabled="true">
                <a href="@(canEditJobInfo?@Url.Action("Index","JobInfo"):"#")">
                    <i>
                        <i class="fa fa-briefcase" aria-hidden="true"></i>
                    </i>
                    <span>اطلاعات شغلی</span>
                </a>
            </li>
            <li role="tab" class="@(Model==9?"current":"disabled") @(Model>9?"done":"")" aria-disabled="true">
                <a href="@(canEditFinancialInfo?@Url.Action("Index","FinancialInfo"):"#")">
                    <i>
                        <i class="fa fa-money" aria-hidden="true"></i>
                    </i>
                    <span>اطلاعات مالی</span>
                </a>
            </li>
            <li role="tab" class="@(Model==10?"current":"disabled") @(Model>10?"done":"")" aria-disabled="true">
                <a href="@(canEditBankingAccount?@Url.Action("Index","BankingAccount"):"#")">
                    <i>
                        <i class="fa fa-credit-card" aria-hidden="true"></i>
                    </i>
                    <span> حساب بانکی</span>
                </a>
            </li>
            <li role="tab" class="@(Model==11?"current":"disabled") @(Model>11?"done":"")" aria-disabled="true">
                <a href="@(canEditConfirm?@Url.Action("Index","Confirm"):"#")">
                    <i>
                        <i class="fa fa-id-badge" aria-hidden="true"></i>
                    </i>
                    <span>تعهدات</span>
                </a>
            </li>

        </ul>
    </div>
</div>