src/Web/Controllers/BaseInfoController.cs
using AutoMapper;
using Cerberus.Domain.Enum;
using Cerberus.Domain.Interface.Services;
using Cerberus.Domain.Model;
using Cerberus.Web.Enum;
using Cerberus.Web.Extensions;
using Cerberus.Web.Filters;
using Cerberus.Web.ViewModel.LegalPerson;
using Cerberus.Web.ViewModel.PrivatePerson;
using Cerberus.Web.WebLogic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using System.Threading.Tasks;
using Cerberus.Domain;
using Cerberus.Domain.Extensions;
using Cerberus.Domain.Interface.Inquiries;
using Cerberus.Domain.Interface.Services.Membership;
using Cerberus.Domain.Model.Membership;
using Cerberus.Utility;
using Cerberus.Web.MappingProfile;
using Gatekeeper.AspModules.ActionFilter;
using Profile = Cerberus.Domain.Model.Profile;
using ProfileExtensions = Cerberus.Domain.Extensions.ProfileExtensions;

namespace Cerberus.Web.Controllers
{

    public class BaseInfoController : BaseController
    {
        private readonly IProfileService _profileService;
        private readonly IPrivatePersonService _privatePersonService;
        private readonly ILegalPersonService _legalPersonService;
        private readonly ICountryService _countryService;
        private readonly IMapper _mapper;
        private readonly IMembershipService _membershipService;
        private readonly IProfilePackageService _profilePackageService;
        private readonly IOfflineTaskService _offlineTaskService;
        private readonly IProfileHistoryService _profileHistoryService;
        public BaseInfoController(IProfileService profileService, IPrivatePersonService privatePersonService, ILegalPersonService legalPersonService, ICountryService countryService, IMapper mapper, IMembershipService membershipService, IProfilePackageService profilePackageService, IOfflineTaskService offlineTaskService, IProfileHistoryService profileHistoryService)
        {
            _profileService = profileService;
            _privatePersonService = privatePersonService;
            _legalPersonService = legalPersonService;
            _countryService = countryService;
            _mapper = mapper;
            _membershipService = membershipService;
            _profilePackageService = profilePackageService;
            _offlineTaskService = offlineTaskService;
            _profileHistoryService = profileHistoryService;
        }

        [HttpGet]
        [Route("baseInfo")]
        [AuthorizeUserFilterFactory(Scope = (int)AvailableScope.BaseInfo)]
        [RateLimitFilterFactory(Order = 1, Limit = 20, PeriodInSec = 1 * 60 * 5, UserIdentifier = "ProfileId")]
        [LogWebRequestFilterFactory(Order = 2)]
        public async Task<IActionResult> Index()
        {
            //show uniqueIdentifier as readonly field 
            var profile = await _profileService.GetAsync(User.ProfileId);
            if (User.ProfileOwnerType == ProfileOwnerType.IranianPrivatePerson)
            {
                var privatePersonModel = await _privatePersonService.GetByProfileIdAsync(User.ProfileId);
                if (privatePersonModel != null)
                {
                    var privatePersonNativeViewModel = _mapper.Map<CreatePrivatePersonNativeViewModel>(privatePersonModel);
                    privatePersonNativeViewModel.UniqueIdentifier = profile.UniqueIdentifier;
                    return View("Native", privatePersonNativeViewModel);
                }
                else
                {
                    if (User.ServiceId.HasValue && User.ServiceId.Value > 0)
                    {
                        var personTmp = await _membershipService.GetPrivatePersonAsync(profile.UniqueIdentifier, profile.Mobile.ToString(), User.ServiceId.Value);
                        if (personTmp != null)
                        {
                            var privatePersonNativeViewModel = _mapper.Map<CreatePrivatePersonNativeViewModel>(personTmp);
                            privatePersonNativeViewModel.UniqueIdentifier = profile.UniqueIdentifier;
                            return View("Native", privatePersonNativeViewModel);
                        }

                        return View("Native", new CreatePrivatePersonNativeViewModel()
                        {
                            UniqueIdentifier = profile.UniqueIdentifier
                        });

                    }
                    return View("Native", new CreatePrivatePersonNativeViewModel()
                    {
                        UniqueIdentifier = profile.UniqueIdentifier
                    });
                }
            }
            if (User.ProfileOwnerType == ProfileOwnerType.IranianLegalPerson)
            {
                var legalPersonModel = await _legalPersonService.GetByProfileIdAsync(User.ProfileId);
                ViewBag.Countries = new SelectList(await _countryService.GetListAsync(), "Id", "Name");
                if (legalPersonModel != null)
                {
                    var createLegalPersonViewModel = _mapper.Map<CreateLegalPersonViewModel>(legalPersonModel);
                    createLegalPersonViewModel.UniqueIdentifier = profile.UniqueIdentifier;
                    return View("Legal", createLegalPersonViewModel);
                }
                return View("Legal", new CreateLegalPersonViewModel()
                {
                    UniqueIdentifier = profile.UniqueIdentifier
                });

            }
            if (User.ProfileOwnerType == ProfileOwnerType.ForeignPrivatePerson)
            {
                var privatePersonModel = await _privatePersonService.GetByProfileIdAsync(User.ProfileId);

                CreatePrivatePersonForeignViewModel createPrivatePersonForeignViewModel = _mapper.Map<CreatePrivatePersonForeignViewModel>(privatePersonModel);

                ViewBag.Countries = new SelectList(await _countryService.GetListAsync(), "Id", "Name");

                return View("Foreign", createPrivatePersonForeignViewModel);
            }


            throw new NotImplementedException();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("baseInfo/privatePerson/foreign")]
        [AuthorizeUserFilterFactory(Scope = (int)AvailableScope.BaseInfo)]
        [RateLimitFilterFactory(Order = 1, Limit = 10, PeriodInSec = 1 * 60 * 5, UserIdentifier = "ProfileId")]
        [LogWebRequestFilterFactory(Order = 2)]
        public async Task<IActionResult> CreateForeignAsync(CreatePrivatePersonForeignViewModel model)
        {
            if (User.ProfileOwnerType != ProfileOwnerType.ForeignPrivatePerson)
            {
                Alert("اطلاعات شما معتبر نمی باشد", NotificationType.Error);
                return RedirectToAction("SignOut", "Session");
            }
            if (!ModelState.IsValid)
            {
                Alert(ModelState.ToErrorMessage(), NotificationType.Error);
                return View("Foreign", model);
            }

            var mappedObject = _mapper.Map<CreatePrivatePersonForeignViewModel, PrivatePerson>(model);

            var dbObject = await _privatePersonService.GetByProfileIdAsync(User.ProfileId);

            if (dbObject != null)
            {
                mappedObject.Id = dbObject.Id;
                mappedObject.ImageId = dbObject.ImageId;
                mappedObject.IsConfirmed = null;
                mappedObject.ProfileId = User.ProfileId;
                mappedObject.CreationDate = DateTime.Now;

                await _privatePersonService.UpdateAsync(mappedObject);
            }
            else
            {
                mappedObject.ProfileId = User.ProfileId;

                await _privatePersonService.CreateAsync(mappedObject);
            }

            return RedirectToAction("Index", "Address");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("baseInfo/privatePerson/iranian")]
        [AuthorizeUserFilterFactory(Scope = (int)AvailableScope.BaseInfo)]
        [RateLimitFilterFactory(Order = 1, Limit = 10, PeriodInSec = 1 * 60 * 5, UserIdentifier = "ProfileId")]
        [LogWebRequestFilterFactory(Order = 2)]
        public async Task<IActionResult> CreateNativeAsync(CreatePrivatePersonNativeViewModel model)
        {
       
            if (User.ProfileOwnerType != ProfileOwnerType.IranianPrivatePerson)
            {
                Alert("اطلاعات شما معتبر نمی باشد", NotificationType.Error);
                return RedirectToAction("SignOut", "Session");
            }

            var profile = await _profileService.GetAsync(User.ProfileId);
            //show uniqueIdentifier as readonly field 
            model.UniqueIdentifier = profile.UniqueIdentifier;
            if (!ModelState.IsValid)
            {
                Alert(ModelState.ToErrorMessage(), NotificationType.Error);

                return View("Native", model);
            }



            var mappedObject = _mapper.Map<CreatePrivatePersonNativeViewModel, PrivatePerson>(model);

            var oldPerson = await _privatePersonService.GetByProfileIdAsync(User.ProfileId);
            var currentStep = oldPerson?.IsConfirmed == false ? CurrentStep.FinancialInfo : CurrentStep.BaseInfo;

            if (oldPerson != null)
            {
                if (oldPerson.Locked)
                {
                    Alert("اطلاعات هویتی شما قابل ویرایش نمی باشد", NotificationType.Error);
                    return View("Native", model);
                }

                mappedObject.Id = oldPerson.Id;
                mappedObject.ImageId = oldPerson.ImageId;
                mappedObject.IsConfirmed = null;
                mappedObject.ProfileId = User.ProfileId;
                mappedObject.CreationDate = DateTime.Now;

                await _privatePersonService.UpdateAsync(mappedObject);

            }
            else
            {
                mappedObject.ProfileId = User.ProfileId;

                await _privatePersonService.CreateAsync(mappedObject);

            }

src/Web/Controllers/DashboardController.cs
using System;
using System.Threading.Tasks;
using AutoMapper;
using Cerberus.Domain.Enum;
using Cerberus.Domain.Interface.Services;
using Cerberus.Web.Enum;
using Cerberus.Web.Filters;
using Cerberus.Web.ViewModel.Dashboard;
using Cerberus.Web.WebLogic;
using Gatekeeper.AspModules.ActionFilter;
using Microsoft.AspNetCore.Mvc;

namespace Cerberus.Web.Controllers
{
    public class DashboardController : BaseController
    {
        private readonly IProfileService _profileService;
        private readonly IMapper _mapper;

        public DashboardController(IProfileService profileService, IMapper mapper)
        {
            _profileService = profileService;
            _mapper = mapper;
        }

        [HttpGet("dashboard")]
        [AuthorizeUserFilterFactory(Scope = (int)AvailableScope.Dashboard)]
        [RateLimitFilterFactory(Order = 1, Limit = 20, PeriodInSec = 1 * 60 * 5, UserIdentifier = "ProfileId")]
        [LogWebRequestFilterFactory(Order = 2)]
        public async Task<IActionResult> Index()
        {
            var result = await _profileService.GetRelatedDataForDashboard(User.ProfileId, User.ProfileOwnerType);
            switch (User.ProfileOwnerType)
            {
                case ProfileOwnerType.IranianPrivatePerson:

                    var privatePersonViewModel = _mapper.Map<Domain.Model.Profile, PrivatePersonDashboardViewModel>(result);
                    return View("PrivatePersonDashboard", privatePersonViewModel);

                case ProfileOwnerType.IranianLegalPerson:   

                    var legalPersonViewModel = _mapper.Map<Domain.Model.Profile, LegalPersonDashboardViewModel>(result);
                    return View("LegalPersonDashboard", legalPersonViewModel);

                case ProfileOwnerType.ForeignPrivatePerson:
                    break;
                case ProfileOwnerType.ForeignLegalPerson:
                    break;
            }

            
            throw new NotImplementedException();
        }
    }
}

src/Web/Views/BaseInfo/EditPrivatePerson.cshtml
@model Cerberus.Web.ViewModel.PrivatePerson.CreatePrivatePersonNativeViewModel

@using Cerberus.Domain.Enum
@using Cerberus.Utility

@{
    ViewBag.HeaderIconClass = "fa fa fa-user";
    ViewBag.Title = "اطلاعات هویتی";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="form-wrapper">

    <div class="form-steps">
        <div class="row margin-bottom-30">
            <div class="col-md-8 col-md-offset-2 text-center">
                <label class="form-label">اطلاعات هویتی شما در سامانه سجام</label>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="form-group">
                    <label class="form-label"> @Html.DisplayNameFor(model => model.FirstName) </label>
                    @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control disabletext", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="form-group">
                    <label class="form-label"> @Html.DisplayNameFor(model => model.LastName) </label>
                    @Html.TextBoxFor(model => model.LastName, new { @class = "form-control disabletext", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="form-group">
                    <label class="form-label"> @Html.DisplayNameFor(model => model.BirthDate) </label>
                    @Html.TextBoxFor(model => model.BirthDate,
                        new
                        {
                            data_placement = "bottom",
                            data_format = "yyyy/MM/dd",
                            @readonly = "readonly",
                            type = "text",
                            @class = "form-control text-center disabletext",

                        })
                    @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="form-group">
                    <label class="form-label"> جنسیت:</label>
                    <span class="form-select">
                        @Html.TextBox("Gender", Model?.Gender.GetEnumDescription(), new { @class = "form-control disabletext", @readonly = "readonly" })
                    </span>
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row margin-bottom-30">
            <div class="col-lg-3 col-md-6">
                <div class="form-group">
                    <label class="form-label"> @Html.DisplayNameFor(model => model.FatherName)</label>
                    @Html.TextBoxFor(model => model.FatherName, new { @class = "form-control disabletext", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="form-group">
                    <label class="form-label"> @Html.DisplayNameFor(model => model.ShNumber) </label>
                    @Html.TextBoxFor(model => model.ShNumber, new { @class = "form-control disabletext", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.ShNumber, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="form-group">

                    <label class="form-label">سری و سریال شناسنامه:</label>
                    <div class="row mrg0L mrg0R">
                        <div class="col-md-5 pad5L pad0R">
                            @Html.TextBoxFor(model => model.Serial, null, new { @Class = "form-control disabletext", @readonly = "readonly", @placeholder = "123456" })
                            @Html.ValidationMessageFor(model => model.Serial, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-4 pad5L pad0R">
                            @Html.TextBoxFor(model => model.SeriSh, null, new { @Class = "form-control disabletext", @readonly = "readonly", @placeholder = "12" })
                            @Html.ValidationMessageFor(model => model.SeriSh, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-3 pad0L pad0R">
                            @Html.TextBoxFor(model => model.SeriShChar, new { @class = "form-control disabletext", @readonly = "readonly" })

                            @Html.ValidationMessageFor(model => model.SeriShChar, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @if (ViewBag?.package == "payment")
        {
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <label class="form-label">برای تغییر اطلاعات هویتی، شما باید قبلا عملیات پرداخت را انجام دهید</label>
                    <form action="@Url.Action("EditAsync", "Payment")" method="post" id="form">
                        @Html.AntiForgeryToken()
                        @Html.Hidden("type", PrimitivePackageType.EditPrivatePersonInfo)
                        <div class="btn-wrapper text-left">
                            <a href="@Url.Action("Index","Dashboard")" class="btn btn-main-outlined">بازگشت</a>
                            <button type="submit" class="btn btn-main" id="confirmBtn"><i class="fa fa-check" aria-hidden="true"></i> پرداخت</button>
                        </div>

                    </form>
                </div>
            </div>
        }
        else if (ViewBag?.package == "access")
        {

            <form action="@Url.Action("UpdatePrivatePerson", "BaseInfo")" method="post" id="form">
                <div class="btn-wrapper text-left">
                    <a href="@Url.Action("Index","Dashboard")" class="btn btn-main-outlined">بازگشت</a>
                    <button type="submit"
                            class="btn btn-main" id="btnSubmit">
                        <i class="fa fa-check" aria-hidden="true"></i>
                        <span>بروز رسانی</span>
                    </button>
                </div>
            </form>

        }
        else if (ViewBag?.package == "accessDenied")
        {
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <label class="alert alert-danger">شما نمی توانید اطلاعات هویتی خود را بروز رسانی نمایید</label>

                    <div class="col-md-4 col-md-offset-4">
                        <div class="btn-wrapper text-left">
                            <a href="@Url.Action("Index","Dashboard")" class="btn btn-main-outlined">بازگشت</a>

                        </div>
                    </div>
                </div>
            </div>

        }

    </div>

</div>

src/Web/Views/BaseInfo/Foreign.cshtml
@model Cerberus.Web.ViewModel.PrivatePerson.CreatePrivatePersonForeignViewModel

@using static Cerberus.Utility.Tools
@using static Cerberus.Utility.PersianDateExtension

@{
    ViewBag.Title = "اطلاعات هویتی";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="form-wrapper">
    <h3 tabindex="-1" class="title-form">
        <i>
            <i class="fa fa-male" aria-hidden="true"></i>
        </i>
        <span>اطلاعات هویتی</span>
    </h3>
    <form action="@Url.Action("CreateForeignAsync","BaseInfo")" method="post">

        @Html.AntiForgeryToken()

        <div class="form-steps">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.FirstName) </label>
                        @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.LastName) </label>
                        @Html.TextBoxFor(model => model.LastName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.BirthDate) </label>
                        @Html.TextBoxFor(model => model.BirthDate,
                            new
                            {
                                data_placement = "bottom",
                                data_format = "yyyy/MM/dd",
                                data_trigger = "focus",
                                @readonly = "readonly",
                                data_targetselector = "#BirthDate",
                                type = "text",
                                @class = "form-control text-center",
                                data_mddatetimepicker = "true"
                            })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> جنسیت:</label>
                        <span class="form-select">
                            @Html.DropDownListFor(model => model.Gender, ToSelectList<Cerberus.Domain.Enum.Gender>(), "جنسیت را انتخاب کنید", new { @class = "form-control" })
                        </span>
                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.FatherName)</label>
                        @Html.TextBoxFor(model => model.FatherName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.BornCountryId) </label>
                        <span class="form-select">
                            @Html.DropDownListFor(model => model.BornCountryId, ViewBag.Countries as SelectList, "کشور محل تولد را انتخاب کنید", new { @class = "form-control" })
                        </span>
                        @Html.ValidationMessageFor(model => model.BornCountryId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.EvidenceType) </label>
                        <span class="form-select">
                            @Html.DropDownListFor(model => model.EvidenceType, ToSelectList<Cerberus.Domain.Enum.EvidenceType>(), "نوع مدرک را انتخاب کنید", new { @class = "form-control" })
                        </span>
                        @Html.ValidationMessageFor(model => model.EvidenceType, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.EvidenceCountryId)</label>
                        @Html.DropDownListFor(model => model.EvidenceCountryId, ViewBag.Countries as SelectList, "کشور صادر کننده مدرک را انتخاب کنید", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.EvidenceCountryId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.EvidenceNumber)</label>
                        @Html.TextBoxFor(model => model.EvidenceNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.EvidenceNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.EvidenceExpirationDate) </label>
                        @Html.TextBoxFor(model => model.EvidenceExpirationDate, new
                        {
                            data_placement = "bottom",
                            data_format = "yyyy/MM/dd",
                            data_trigger = "focus",
                            @readonly = "readonly",
                            data_targetselector = "#EvidenceExpirationDate",
                            type = "text",
                            @class = "form-control text-center",
                            data_mddatetimepicker = "true"
                        })
                        @Html.ValidationMessageFor(model => model.EvidenceExpirationDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.CitizenCountryId) </label>
                        @Html.DropDownListFor(model => model.CitizenCountryId, ViewBag.Countries as SelectList, "تابعیت خود را انتخاب کنید", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CitizenCountryId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.PassportNumber)</label>
                        @Html.TextBoxFor(model => model.PassportNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PassportNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.SpecialNumber)</label>
                        @Html.TextBoxFor(model => model.SpecialNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SpecialNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.LicenseNumber) </label>
                        @Html.TextBoxFor(model => model.LicenseNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LicenseNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.LicenseIssueDate) </label>
                        @Html.TextBoxFor(model => model.LicenseIssueDate,
    new
    {
                            data_placement = "bottom",
                            data_format = "yyyy/MM/dd",
                            data_trigger = "focus",
                            @readonly = "readonly",
                            data_targetselector = "#LicenseIssueDate",
                            type = "text",
                            @class = "form-control text-center",
                            data_mddatetimepicker = "true"
                        })
                        @Html.ValidationMessageFor(model => model.LicenseIssueDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.LicenseExpirationDate)</label>
                        @Html.TextBoxFor(model => model.LicenseExpirationDate,new
                        {
                            data_placement = "bottom",
                            data_format = "yyyy/MM/dd",
                            data_trigger = "focus",
                            @readonly = "readonly",
                            data_targetselector = "#LicenseExpirationDate",
                            type = "text",
                            @class = "form-control text-center",
                            data_mddatetimepicker = "true"
                        })
                        @Html.ValidationMessageFor(model => model.LicenseExpirationDate, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="form-group">
                        <label class="form-label"><span class="mrg5L color-red">*</span> @Html.DisplayNameFor(model => model.Description)</label>
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="btn-wrapper">
                <button type="submit" class="btn btn-default"><i class="fa fa-check" aria-hidden="true"></i> ذخیره</button>
            </div>
        </div>
    </form>
</div>